---
- name: Load secrets
  ansible.builtin.include_tasks: secrets.yml

- name: Delete old web content
  file:
    path: /home/web/data/public
    state: absent

- name: Delete old generated public content
  file:
    path: "{{ role_path }}/files/hugo/public"
    state: absent
  delegate_to: localhost

- name: Delete old generated resources
  file:
    path: "{{ role_path }}/files/hugo/resources"
    state: absent
  delegate_to: localhost

- name: Generate static content (Hugo)
  shell: "cd {{ role_path }}/files/hugo && hugo build --ignoreCache --buildDrafts --buildFuture --buildExpired"
  delegate_to: localhost

- name: Transfer web content
  ansible.posix.synchronize:
    src: "{{ role_path }}/files/hugo/public"
    dest: /home/web/data

- name: Transfer docker-compose.yml
  copy: src=docker-compose.yml dest=~/ mode=0755

- name: Transfer nginx.conf
  copy: src=nginx.conf dest=~/data/nginx.conf mode=0755

# - name: Create back-end config directory
#   ansible.builtin.file:
#     path: ~/back
#     state: directory
#     mode: 0755

# - name: Create config.yml
#   ansible.builtin.template:
#     src: config.yml.j2
#     dest: ~/back/config.yml
#     mode: 0755

- name: Compose down
  shell: docker-compose down

- name: Compose up
  shell: docker-compose up -d --quiet-pull
