baseUrl      = "https://jackavery.ca/"
title        = "jackavery.ca"
languageCode = "en-us"
theme        = "hello-friend-ng"

[pagination]
  pagerSize = 10

[permalinks]
  posts = "/posts/:year/:month/:title/"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "canadian dude making stuff for games"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = true

  # Metadata mostly used in document's head
  description = "jackavery.ca"
  keywords = "homepage"
  images = [""]

  [[params.social]]
    name = "github"
    url = "https://github.com/jack-avery/"

  [[params.social]]
    name = "email"
    url = "mailto:jack.avery.business@gmail.com"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "jackavery.ca"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "read other posts"

  [languages.en.params]
    [languages.en.params.logo]
      logoText = "jackavery.ca"
      logoHomeLink = "/"

  [[menu.main]]
    identifier = "blog"
    name       = "blog"
    url        = "/posts"