---
- name: Create build directory
  ansible.builtin.file:
    path: ~/build/back
    state: directory
    mode: "0755"

- name: Copy build sources
  ansible.builtin.synchronize:
    src: "{{ role_path }}/files/"
    dest: ~/build/back
    archive: false
    recursive: true
    rsync_opts:
      - "--exclude=target"
      - "--exclude=Cargo.lock"

- name: Prune space before building
  community.docker.docker_prune:
    images: true
    containers: true

- name: Build rocket.rs binary
  community.docker.docker_container:
    name: "jackavery-web-back-build"
    image: "rust:1.70"
    state: started
    auto_remove: true
    volumes:
      - /home/web/build/back:/build
    command: '/build/build.sh'

- name: Wait for container to close
  wait_for:
    path: /home/web/build/back/.lock
    state: absent
    delay: 10

- name: Build image
  community.docker.docker_image:
    name: jackavery-web-back
    tag: latest
    source: build
    force_tag: true
    force_source: true
    build:
      pull: true
      dockerfile: Dockerfile
      platform: linux/arm64/v8
      path: ~/build/back
    state: present
