version: '3'

services:
  front:
    image: "nginx:stable-alpine"
    restart: unless-stopped
    volumes:
      - ./data/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/public:/usr/share/nginx/html
      - ./data/certbot/conf:/etc/letsencrypt:ro
      - ./data/certbot/www:/var/www/certbot:ro
      - ./data/fastdl:/usr/share/nginx/html/fastdl:ro
    ports:
      - 80:80
      - 443:443

  # back:
  #   image: "jackavery-web-back:latest"
  #   restart: unless-stopped
  #   volumes:
  #     - ./back/config.yml:/app/config.yml:ro
  #   ports:
  #     - 8000:8000

  certbot:
    image: "certbot/certbot:arm32v6-latest"
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    network_mode: "host"
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
