version: '3'

services:
  front:
    image: "nginx:stable-alpine"
    restart: unless-stopped
    volumes:
      - ./data/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/web:/usr/share/nginx/html
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./data/fastdl:/usr/share/nginx/html/fastdl
    ports:
      - 80:80
      - 443:443

  back:
    image: "jackavery-web-back:latest"
    restart: unless-stopped
    volumes:
      - ./back/config.yml:/app/config.yml
    ports:
      - 8000:8000

  certbot:
    image: "certbot/certbot:arm32v6-latest"
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    network_mode: "host"
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  git-server:
    image: "rockstorm/git-server"
    volumes:
      - ./.ssh/git.pub:/home/git/.ssh/authorized_keys
      - ./git-repositories:/srv/git
    environment:
      SSH_AUTH_METHODS: "publickey"
      SSH_AUTHORIZED_KEYS_FILE: /home/git/.ssh/authorized_keys
      REPOSITORIES_HOME_LINK: "/srv/git"
    ports:
      - "1617:22"

  git-web:
    image: "rockstorm/gitweb"
    ports:
      - "16171:80"
    volumes:
      - ./git-repositories:/srv/git:ro
