version: '3'

services:
  front:
    image: "caddy:alpine"
    restart: unless-stopped
    volumes:
      - ./data/Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy:/data
      - ./data/web:/usr/share/caddy
      - ./data/fastdl:/usr/share/caddy/fastdl
    ports:
      - 80:80
      - 443:443

  back:
    image: "jackavery-web-back:latest"
    restart: unless-stopped
    volumes:
      - ./back/config.yml:/app/config.yml
    ports:
      - 8000:8000
